using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using emde.kz.Models;
using System.Data.Entity;

namespace emde.kz.DAL
{

    public class MedicinesInitializer : System.Data.Entity.DropCreateDatabaseAlways<MedicinesContext>
    {
        protected override void Seed(MedicinesContext context)
        {
            var cities = new List<City>
            {
                new City{CityID = 1, CityName = "Алматы", SrcYandexCity="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=_hDqJ_HbZm3Qfn_EYyLDfVEso6UEz5b3&amp;width=1098&amp;height=500&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
        		new City{CityID = 2, CityName = "Астана", SrcYandexCity="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=RTLtnrjftG2r-4GUe8N_F6Izv2gsoZrV&amp;width=1098&amp;height=500&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new City{CityID = 3, CityName = "Атырау", SrcYandexCity=""},
                new City{CityID = 4, CityName = "Актау", SrcYandexCity=""},
                new City{CityID = 5, CityName = "Актюбинск", SrcYandexCity=""},
                new City{CityID = 6, CityName = "Жезказган", SrcYandexCity=""},
                new City{CityID = 7, CityName = "Жанаозен", SrcYandexCity=""},
                new City{CityID = 8, CityName = "Караганда", SrcYandexCity=""},
                new City{CityID = 9, CityName = "Кокшетау", SrcYandexCity=""},
                new City{CityID = 10, CityName = "Костанай", SrcYandexCity=""},
                new City{CityID = 11, CityName = "Кызылорда", SrcYandexCity=""},
                new City{CityID = 12, CityName = "Павлодар", SrcYandexCity=""},
                new City{CityID = 13, CityName = "Петропавловск", SrcYandexCity=""},
                new City{CityID = 14, CityName = "Рудный", SrcYandexCity=""},
                new City{CityID = 15, CityName = "Семей", SrcYandexCity=""},
                new City{CityID = 16, CityName = "Талдыкорган", SrcYandexCity=""},
                new City{CityID = 17, CityName = "Тараз", SrcYandexCity=""},
                new City{CityID = 18, CityName = "Темиртау", SrcYandexCity=""},
                new City{CityID = 19, CityName = "Туркестан", SrcYandexCity=""},
                new City{CityID = 20, CityName = "Уральск", SrcYandexCity=""},
                new City{CityID = 21, CityName = "Усть-Каменогорск", SrcYandexCity=""},
                new City{CityID = 22, CityName = "Шымкент", SrcYandexCity=""},
                new City{CityID = 23, CityName = "Экибастуз", SrcYandexCity=""}

            };

            cities.ForEach(s => context.Cities.Add(s));
            context.SaveChanges();

            var hospitals = new List<Hospital>
            {
                new Hospital {ID = 1, CityID = 1, Name = "Алматинская многопрофильная клиническая больница", Address = "улица Демченко, 83", PhoneNumber = "+7 (728) 241-12-12", Email = "amkb_pr@mail.ru", Website = "http://amkb.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=N5Ap7BATU2jS7e1hm77lupeiZFXA9lKh&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=N5Ap7BATU2jS7e1hm77lupeiZFXA9lKh&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 2, CityID = 1, Name = "Городская больница скорой неотложной помощи", Address = "улица Казыбек Би 96", PhoneNumber = "+7 727 292 3101", Email = "gbsnp@mail.ru", Website = "http://www.gbsnp.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=fNix-a_rc6v6TLIOZQRfm_vPykx4KK8X&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=fNix-a_rc6v6TLIOZQRfm_vPykx4KK8X&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 3, CityID = 1, Name = "Военный Клинический Госпиталь МО РК", Address = "ул. Красногорская, 2", PhoneNumber = "+7 (727) 290-21-01", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=I0ogWRxOU85ixIm-A37P0JkljAPOaspp&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=I0ogWRxOU85ixIm-A37P0JkljAPOaspp&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 4, CityID = 1, Name = "Городская больница Алатау", Address = "Медеуский район, поселок Алатау,  ул. Жетбаева, д. 28", PhoneNumber = "+7 (727) 386-53-03", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=Wsv1iZ0HmtQEgswxAyLysgqR7hbKgjG8&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=Wsv1iZ0HmtQEgswxAyLysgqR7hbKgjG8&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 5, CityID = 1, Name = "Городская больница сестринского ухода", Address = "мкр.Коктем-3, д. 11", PhoneNumber = "+7 (727)-394-51-50", Email = "gbsu_almaty@mail.ru", Website = "http://gbsu.kz/index.php/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=XZlRF8HiU3lfiuti2k-oMKWXD-fWBu7v&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=XZlRF8HiU3lfiuti2k-oMKWXD-fWBu7v&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 6, CityID = 1, Name = "Городская инфекционная клиническая больница", Address = "ул. Байзакова, д. 295", PhoneNumber = "+7 (727)-274-72-21 ", Email = "gu.gkib@mail.ru", Website = "http://www.gkib.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=BImt7IgHwaXuqBAG6qiJyOxeZn6Em-9G&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=BImt7IgHwaXuqBAG6qiJyOxeZn6Em-9G&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 7, CityID = 1, Name = "Городская клиническая больница №1", Address = "Микрорайон «Калкаман-2», улица Ауэзова, 2 ", PhoneNumber = "+7 (727) 270-87-34", Email = "нет информации", Website = "http://www.agkb1.kz", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=TLrQUy7hDhediKkaIccUSY3vuX2jHt1-&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=TLrQUy7hDhediKkaIccUSY3vuX2jHt1-&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 8, CityID = 1, Name = "Городская клиническая больница №4", Address = "ул. Папанина, д. 220", PhoneNumber = "+7 (727) 983-29-16", Email = "info@gkb4.kz", Website = "http://gkb4-almaty.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=QTDdu_ZxWivHBbLED_eom8cvNmcgHkY2&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=QTDdu_ZxWivHBbLED_eom8cvNmcgHkY2&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 9, CityID = 1, Name = "Городская клиническая больница №5", Address = "пр. Достык, д. 220", PhoneNumber = "+7 (727) 264 77 62", Email = "нет информации", Website = "http://гкб5.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=9ukZOq1odbn9WANxs-s-bRyp-cc1zvzz&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=9ukZOq1odbn9WANxs-s-bRyp-cc1zvzz&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 10, CityID = 1, Name = "Городская клиническая больница №7", Address = "Микрорайон «Калкаман-2», улица Ауэзова", PhoneNumber = "+7 (727) 270-86-14", Email = "info@gkb7.kz", Website = "http://www.gkb7.kz/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=CLnr-3dKNko4alpZUTIMxE6-5WbbieD6&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=CLnr-3dKNko4alpZUTIMxE6-5WbbieD6&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 11, CityID = 1, Name = "Городской кардиологический центр", Address = "ул. Толе би, д. 93", PhoneNumber = "+7 (727) 225 00 67", Email = "kardiocenter-almaty@yandex.ru", Website = "http://kardio-almaty.kz/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=FVJgUbc6F7uyaMFGf9Hfgm4BjCCzKZ4B&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=FVJgUbc6F7uyaMFGf9Hfgm4BjCCzKZ4B&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 12, CityID = 1, Name = "Городской кожно-венерологический диспансер", Address = "ул. Манаса, д. 65", PhoneNumber = "+7 (727) 2740195", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=tLE1cYH_EsmNq3x-pDeHJhUyhF38_7Mv&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=tLE1cYH_EsmNq3x-pDeHJhUyhF38_7Mv&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 13, CityID = 1, Name = "Городской онкологический диспансер", Address = "ул. Утепова, 3", PhoneNumber = "+7 (727) 382 6160", Email = "almaty.onco@mail.ru", Website = "http://www.oncologycenter.kz/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=6wCOnRWnYLPh1nBWTT1h-PRGO2MD5nfD&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=6wCOnRWnYLPh1nBWTT1h-PRGO2MD5nfD&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 14, CityID = 1, Name = "Городской наркологический центр медико-социальной коррекции", Address = "ул. Макатаева, 10", PhoneNumber = "+7 (727) 382-35-59", Email = "gncmck@mail.ru", Website = "http://www.gncmsk.kz/index.php/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=8UjiQMnSgGDXsKzAJXrGPAgnR-Q8Nl1y&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=8UjiQMnSgGDXsKzAJXrGPAgnR-Q8Nl1y&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 15, CityID = 1, Name = "Городской ревматологический центр", Address = "ул. Айтеке би, д. 116", PhoneNumber = "+7 (727) 233-17-71", Email = "revmatolog.kaz@gmail.com", Website = "http://revmatolog.kz/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=S1yMCFuB_egNVNPqYaBjdeUud0hdJARV&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=S1yMCFuB_egNVNPqYaBjdeUud0hdJARV&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 16, CityID = 1, Name = "Городской центр психического здоровья", Address = "ул. Каблукова, д. 117", PhoneNumber = "+ 7 (727) 376-55-95", Email = "kablukova117A@mail.ru", Website = "http://www.cpzalmaty.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=bkJTgnoWEcDVRyvqcXP718lND9BL9xV1&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=bkJTgnoWEcDVRyvqcXP718lND9BL9xV1&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 17, CityID = 1, Name = "Городской центр репродукции человека", Address = "ул. Торекулова, д. 73", PhoneNumber = "+7 (727) 279 02 11", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=RwbbWTU8VeMvBg96Zj9GNoDXCYpTdoe9&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=RwbbWTU8VeMvBg96Zj9GNoDXCYpTdoe9&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 18, CityID = 1, Name = "Госпиталь МВД РК", Address = "ул. Ходжанова, д. 17", PhoneNumber = "+7 (727) 247 64 57", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=HSnHzxqUrlRDdNiquOXjJNBZm4L5OKOH&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=HSnHzxqUrlRDdNiquOXjJNBZm4L5OKOH&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 19, CityID = 1, Name = "Детская городская клиническая больница №1", Address = " ул. Манаса, 40", PhoneNumber = "+7 (727) 274-45-43", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=FTrHNXVmjXs246XQ-Ks0sp6OI0nLNFbQ&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=FTrHNXVmjXs246XQ-Ks0sp6OI0nLNFbQ&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 20, CityID = 1, Name = "Детская городская клиническая больница №2", Address = "пр. Алтынсарина, д. 54", PhoneNumber = "+7 (727) 277 38 61", Email = "dgkb-2@mail.ru", Website = "http://www.dgkb2.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ZOllTyBtYb1StWmUXbZByMJZZ-7222nA&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ZOllTyBtYb1StWmUXbZByMJZZ-7222nA&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 21, CityID = 1, Name = "Детская городская клиническая инфекционная больница", Address = "Байзакова 299а", PhoneNumber = "+7 (727) 394-88-17", Email = "dgkib@bk.ru", Website = "http://www.childhospital.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=nMvRV3RkBKl2hVtldzs35kXvRv3-YGub&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=nMvRV3RkBKl2hVtldzs35kXvRv3-YGub&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 22, CityID = 1, Name = "Детская железнодорожная больница", Address = "улица Майбороды, 29", PhoneNumber = "+7 (727) 235-12-75", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=kTI5GztFpvnodldzF3Li-2NKy7wwjSB2&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=kTI5GztFpvnodldzF3Li-2NKy7wwjSB2&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 23, CityID = 1, Name = "Железнодорожная больница станции Алматы-1", Address = "Акан Серы 36", PhoneNumber = "+7 (727) 221–49–42", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=BjCXdxRULddlLbMrQIFjVKCbCSzS8C4A&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=BjCXdxRULddlLbMrQIFjVKCbCSzS8C4A&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 24, CityID = 1, Name = "Казахский научно-исследовательский институт глазных болезней", Address = "улица Толе би, 95А", PhoneNumber = "+7 (727) 279 54 36", Email = "kaznii.gb@mail.ru", Website = "http://eyeinst.kz/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=sSwcbg5DMr_FAxwS0qV7LJpOFDoaA8kw&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=sSwcbg5DMr_FAxwS0qV7LJpOFDoaA8kw&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 25, CityID = 1, Name = "Казахский научно-исследовательский институт онкологии и радиологии", Address = "пр. Абая, д. 91", PhoneNumber = "+7 (727) 349-30-99", Email = "admin@ncc.org.kz", Website = "http://www.onco.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=_2t1_FAMRh4b0kZR1TIzgnXdwmzW3C9h&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=_2t1_FAMRh4b0kZR1TIzgnXdwmzW3C9h&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 26, CityID = 1, Name = "Клиническая дорожная больница, филиал АО Железнодорожные госпитали медицина катастроф", Address = "ул. Масанчи, д. 92", PhoneNumber = "+7 (727) 292-38-00", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=JMPQ7srWkaPSqoCO6YrE3Ss9LHPMRiLD&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=JMPQ7srWkaPSqoCO6YrE3Ss9LHPMRiLD&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 27, CityID = 1, Name = "Научно-исследовательский институт кардиологии и внутренних болезней", Address = "ул. Айтеке би 120", PhoneNumber = "+7 (727) 233-00-61", Email = "нет информации", Website = "http://www.ncvb.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=1IUso_7zOiqBISZTOX6v7NsnbCVN8VEq&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=1IUso_7zOiqBISZTOX6v7NsnbCVN8VEq&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 28, CityID = 1, Name = "Научный центр педиатрии и детской хирургии", Address = "пр. Аль-Фараби, д. 146", PhoneNumber = "+7 (727) 299-21-21", Email = "pediatr.kz@mail.ru", Website = "http://www.pediatria.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ZGrUNbVjtWMhbiqK3W2-UwkBDZGhZCEc&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ZGrUNbVjtWMhbiqK3W2-UwkBDZGhZCEc&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 29, CityID = 1, Name = "Научный центр урологии им. академика Б.У. Джарбусынова", Address = "ул. Басенова, д. 2", PhoneNumber = "+7 (727) 246-52-08", Email = "нет информации", Website = "http://www.urology.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=UfDD_7SK9NhobBcQB6f6H-BFA1KQOwDO&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=UfDD_7SK9NhobBcQB6f6H-BFA1KQOwDO&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 30, CityID = 1, Name = "Национальный научный центр хирургии им. А.Н. Сызганова", Address = "ул. Желтоксан, 62", PhoneNumber = "+7 (727) 279 95 22", Email = "info@nnch.kz", Website = "http://nnch.kz", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=67MJe15FiDOLuoxaItoli7szB9Q8upCL&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=67MJe15FiDOLuoxaItoli7szB9Q8upCL&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 31, CityID = 1, Name = "Национальный центр проблем туберкулеза МЗ РК", Address = "ул. К. Бекхожина, д. 5", PhoneNumber = "+7 (727) 293 84 04", Email = "info@ncpt.kz", Website = "http://www.ncpt.kz/ru/node/27", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=zROSV-n2rH3jAwqkVp3W6nSyekJy6rhO&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=zROSV-n2rH3jAwqkVp3W6nSyekJy6rhO&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 32, CityID = 1, Name = "Республиканский клинический госпиталь для инвалидов отечественной войны", Address = "ул.Каблукова, д. 129 А", PhoneNumber = "+7 (727) 395 13 49", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=QXKDCLLfivIFYj-w0T-CRb9ux8ie0RL0&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=QXKDCLLfivIFYj-w0T-CRb9ux8ie0RL0&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 33, CityID = 1, Name = "Республиканский научно-практический центр психиатрии, психотерапии и наркологии алматы", Address = "ул. Амангелды 88", PhoneNumber = "+7 (727) 272 48 32", Email = "info@rnpcppn.kz", Website = "http://rnpcppn.kz/rus/index.html", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=oKjpRYMGVI-BGKbmGYA4ZZl9BGgWEp5u&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=oKjpRYMGVI-BGKbmGYA4ZZl9BGgWEp5u&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 34, CityID = 1, Name = "Центр медицинской помощи", Address = "ул. Пятницкого, 102-А", PhoneNumber = "+7 (727) 229-12-22", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=82fJkqTrkwwcE_rAIur8W_dsqgYqo2-Z&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=82fJkqTrkwwcE_rAIur8W_dsqgYqo2-Z&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 35, CityID = 1, Name = "Республиканский научно-исследовательский центр охраны здоровья матери и ребенка", Address = "проспект Достык 125", PhoneNumber = "+7 (727) 387 08 91", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=VwJfIvLBEtMZ5e86SZiFSdB8xrvTMxFB&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=VwJfIvLBEtMZ5e86SZiFSdB8xrvTMxFB&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 36, CityID = 1, Name = "Центральная городская клиническая больница", Address = "ул Джандосова 6", PhoneNumber = "+7 (727) 274-84-43", Email = "cgkb@mail.ru", Website = "http://www.almaty-cgkb.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=r00UvNKzHFvAbQR4TA--fbhGzCnnmxb7&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=r00UvNKzHFvAbQR4TA--fbhGzCnnmxb7&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 37, CityID = 1, Name = "Центральная клиническая больница медицинского центра Управления делами Президента Республики Казахстан", Address = "ул. Панфилова 139", PhoneNumber = "+7 (727) 261 04 50", Email = "нет информации", Website = "http://sovminka.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=wyL3w7iRCZpzKKfDQPtyAjI5bCGD2w_P&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=wyL3w7iRCZpzKKfDQPtyAjI5bCGD2w_P&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 38, CityID = 1, Name = "Центральный военный клинический госпиталь МО РК", Address = "ул. Жандосова, д. 53", PhoneNumber = "+7 (727) 221-39-34", Email = "нет информации", Website = "нет информации", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=WyL_oR5pEF6FaSPE63faVunjM8eLG2jx&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=WyL_oR5pEF6FaSPE63faVunjM8eLG2jx&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},

                new Hospital {ID = 39, CityID = 2, Name = "Городская больница №1", Address = "ул. Кошкарбаева, 66", PhoneNumber = "+ 7 (7172) 23 16 01", Email = "нет информации", Website = "https://auruhana1.kz/index.php/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=1Hm2Qd7z8QVMNqYgaGmjP8CmpOJv8SJ8&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=1Hm2Qd7z8QVMNqYgaGmjP8CmpOJv8SJ8&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 40, CityID = 2, Name = "Городская больница №2", Address = "пр. Турар Рыскулова 6", PhoneNumber = "+7 (7172) 57-72-45", Email = "astana_clinic360@mail.ru", Website = "http://www.astanaclinic.kz/index.php/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=zEdEk23LoojXIt2ZmiGlGgd02M-3_JrE&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=zEdEk23LoojXIt2ZmiGlGgd02M-3_JrE&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 41, CityID = 2, Name = "Железнодорожная больница", Address = "пр. Женис, 58", PhoneNumber = "+7 (7172) 93-34-02", Email = "centr_zhd@mail.ru", Website = "http://www.cdb-astana.kz/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=8zksrtJq1mMadU413P_iFHTzmiD9jylh&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=8zksrtJq1mMadU413P_iFHTzmiD9jylh&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"},
                new Hospital {ID = 42, CityID = 2, Name = "Городская инфекционная больница", Address = "ул. Манаса 22/3", PhoneNumber = "+7 (7172) 56-11-30", Email = "gib_adm@mail.ru", Website = "http://www.gib.kz/index.php/ru/", SrcYandex = "https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=kR6WytFsBpPKU8cT4Q07wgM3nvJ8Zd_3&amp;width=350&amp;height=250&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true", SrcYandexLarge="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=kR6WytFsBpPKU8cT4Q07wgM3nvJ8Zd_3&amp;width=1100&amp;height=600&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"}
                
            };
            hospitals.ForEach(s => context.Hospitals.Add(s));
            context.SaveChanges();

            var medicines = new List<Medicine>
            {
            new Medicine{Name="Препидил", Type="Гель интрацервикальный", Country="БЕЛЬГИЯ", Company="Пфайзер МФГ", Recipe=true, Dosage="0.5 Миллиграмм", InternationalName="Препидил", Component="1 шприц с 3 г (2, 5 мл) геля включает динопростона 0, 5 мг; другие составляющие: кремния диоксид коллоидный, триацетин", PharmaAction="Стимуляция родов при доношенной беременности, индукция родов при доношенной или почти доношенной беременности, индукция изгнания плода в случае его внутриутробной гибели, медикаментозный аборт, несостоявшийся аборт, пузырный занос.", Contrindiction="Гиперчувствительность; при назначении для индукции родов при доношенной беременности наличие в анамнезе сведений о кесаревом сечении или больших хирургических вмешательствах на матке, трудных и/или травматичных родах, пельвиоперитоните, 6 или более доношенных беременностях; высокая степень несоответствия размеров таза и головки плода; предшествующий дистресс плода, аномальные положения плода. При назначении для индукции родов геля вагинального - немакушечные предлежания плода, инфекции нижних отделов полового тракта, кровянистые выделения из половых путей неуточненного характера во время беременности, вскрывшийся плодный пузырь. При назначении для медикаментозного аборта - инфекция тазовых органов в случае, если не проведена адекватная предшествующая терапия, цервицит или инфекции влагалища (противопоказано экстраамниотическое введение).",
                         Effect="Повышение тонуса матки, тетанические сокращения; тошнота, рвота, диарея, головная боль, головокружение, раздражение тканей, эритема в месте в/в введения, приливы, дрожь, повышение температуры, лейкоцитоз; у плода - нарушения сердечного ритма, асфиксия. ", MethodsOfUse="Для индукции родов при доношенной беременности дозу подбирают в соответствии с чувствительностью пациентки и поддерживают на возможно более низком уровне, обеспечивающем достаточную реакцию матки и нормальное прогрессивное раскрытие шейки. Внутрь в первой дозе 0,5 мг, в последующем - 0,5 мг каждый час. Если активность матки недостаточна, дозу увеличивают до 1 мг/ч, пока активность матки не увеличится. Не рекомендуется увеличивать дозу свыше 1,5 мг/ч. В случае прогрессирующего расширения шейки матки возможно уменьшение дозы до 0,5 мг/ч. Для в/в введения применяют инъекционный раствор с концентрацией 1,5 мкг/мл. Начальная скорость инфузии, которую поддерживают в течение первых 30 мин, составляет 0,25 мкг/мин. Если желаемый эффект не достигнут, то скорость введения увеличивается до 0,5 мкг/мин. В некоторых случаях допускают постепенное увеличение скорости введения до 1 или 2 мкг/мин. В случае возникновения гипертонуса матки или дистресса плода инфузию прекращают до нормализации состояния пациентки и плода, после этого инфузию можно возобновить со скоростью, составляющей 50% от последней, а затем постепенно увеличивать скорость. Для индукции родов возможно также применение вагинального геля в начальной дозе 1 мг. Гель вводят в задний свод влагалища. При необходимости через 6 ч можно ввести вторую дозу геля - 1-2 мг (2 мг назначают в случае полного отсутствия эффекта от первого введения, 1 мг применяют для усиления уже достигнутого эффекта). Для индукции изгнания плода в случае его внутриутробной гибели - в/в инфузия с начальной скоростью 0,5 мкг/мин, с дальнейшим повышением скорости с интервалами не меньше 1 ч.", StorageCondition="2 г.", Image=@"\imgMed\1.jpg"},
            new Medicine{Name="Оспамокс", Type="Порошок для приготовления суспензии для приема внутрь", Country="АВСТРИЯ", Company="Сандоз ГмбХ", Recipe=true, Dosage="125 мг/5 мл", InternationalName="amoxicillin", Component="1 таблетка содержит амоксицилина 500 мг или 1000 мг", PharmaAction="Оспамокс – полусинтетический аминопенициллиновый антибиотик широкого спектра действия для перорального использования. Подавляет синтез клеточной стенки бактерий в период их деления. Благодаря широкому спектру действия препарат высокоактивен против грамнегативных и грампозитивных микроорганизмов: Escherichia coli, Proteus mirabilis, Salmonella spp., Shigella spp., Campilobacter spp., Haemophilus influenzae, Bordetella pertussis, лептоспор, хламидии, Streptococcus pneumoniae, стрептококков групп A, B, C, G, H, I, M; Staphylococcus spp. и Neisseria spp., что не продуцируют пенициллиназу, Erysipelothrix rhysiopathiae, Corynebacterium spp., Bacillus anthracis, актиномицет, стрептобацил, Spirillum minus, Pasteurella multocida, листерии, спирохет, а также разных анаэробных микроорганизмов (в том числе пептококков, пептострептококков, клостридии и фузобактерий).", Contrindiction="Повышенная чувствительность к пенициллинов; а также перекрестная чувствительность к ß-лактамных антибиотиков, таких как цефалоспорины; инфекционный мононуклеоз; лимфолейкоз. Дети до 3 лет (для них рекомендованные детские лекарственные формы препарата: суспензии).",
                         Effect="Желудочно-кишечный тракт: тошнота, потеря аппетита, рвота, вздутие живота, диарея, сухость во рту, нарушение вкуса; редко – обесцвечивания зубов (особенно при применении суспензии), что исчезает после чистки зубов щеткой; очень редко – окраски языка в чёрный цвет. Печенка и желчевыводящие пути: умеренно выраженное и проходящее увеличение активности печеночных трансаминаз. Реакции повышенной чувствительности: побочные реакции со стороны кожи, такие как экзантема, зуд, крапивница; немедленное появление после приема препарата крапивницы свидетельствует про наличие аллергической реакции на амоксицилин, вследствие чего лечения препаратом следует отменить. Редко – мультиформная эритема, макуло-папулезные высыпание; сывороточная болезнь, аллергический васкулит, синдром Стивена-Джонсона, буллезныей и эксфолиативный дерматит; в отдельных случаях – токсический эпидермальный некролиз, анафилактический шок, ангионевротический отек. Нервная система: гиперкинезия, головокружение, судороги. Судороги могут наблюдаться у пациентов с почечной недостаточностью или в тех, кто применяет высокие дозы препарата. Сечовивидна система: редко – развитие интерстициального нефрита. Система кроветворение: редко – агранулоцитоз, тромбоцитопения. Общие нарушения: является единичные сообщения про возникновения лекарственного лихорадки; долговременное или повторное применение препарата может привести до развития суперинфекций и колонизации стойких микроорганизмов или дрожжей, что вызывают оральный или вагинальный кандидоз.", MethodsOfUse="Режим дозировки устанавливают индивидуально, в зависимости от возраста, массы тела и состояния почек больного, а также от чувствительности микроорганизмов и локализации инфекционного процесса. Взрослым как правило назначают по 500 мг 3 раза в сутки. При хронических заболеваниях, рецидивах, тяжёлом течении инфекционных заболеваний назначают до 1 г 3 - 4 раза в сутки. При острой неусложненной гонорей назначают однократно 3 г в объединении с 1 г пробенецида. Для профилактики эндокардиту при небольших хирургических вмешательствах – 3 г за 1 час до проведения процедуры. При необходимости повторную дозу назначают через 6 час. Средний курс лечения – 5 - 7 дней. Для предупреждения осложнений лечения стрептококковых инфекций должно продолжаться как минимум 10 дней. Оспамокс необходимо принимать еще 2 - 3 дня после исчезновения всех симптомов заболевания. При почечной недостаточности (клиренс креатинина < 30 мл/минут) дозу препарата снижают на 15 - 50% и/или увеличивают интервал между приёмами до 12 час. У больных анурией доза препарата не должна превышать 2 г в сутки. Детям Оспамокс назначают в дозах из расчета 30 - 60 мг/кг в сутки, разделенные на 2 - 3 приема.", StorageCondition="3 г.", Image=@"\imgMed\2.jpg"},
            new Medicine{Name="Амикацин", Type="Порошок для приготовления раствора для инъекций", Country="РОССИЯ", Company="Синтез ОАО", Recipe=true, Dosage="500 Миллиграмм", InternationalName=" Amicacinum", Component=" Ампулы по 2 мл, содержащие по 0,1 и 0,5 г амикацина сульфата", PharmaAction="В связи с высокой токсичностью аминогликозиды целесообразно применять короткими курсами в эффективных сочетаниях с другими антибиотиками. При инфекциях, вызванных синегнойной палочкой, высокоэффективна комбинация аминогликозида с карбенициллином. Синергизм также отмечают при сочетании аминогликозида с бензилпенициллином, цефалоспоринами. Вероятность нефротоксических реакций увеличивается при сочетании с метициллином, цефалоридином, сульфаниламидами, фуросемидом. Вероятность аллергических осложнений невысока. Для уменьшения нефротоксического действия аминогликозидов больным рекомендуют обильное питьё. Необходимо избегать совместного назначения с аминогликозидами сильных диуретиков и других лекарственных средств, снижающих канальцевую секрецию.", Contrindiction="Аминогликозиды могут оказывать нефротоксическое и нейротоксическое действие (избирательное поражение VIII черепных нервов). Наиболее опасны ототоксические осложнения аминогликозидов (вплоть до необратимой глухоты) и вестибулярные расстройства. Поражения почек (протеинурия, гематурия) обратимы. Вероятность побочных реакций возрастает при предшествующей патологии органов слуха и почек, у больных со снижением клубочковой фильтрации (в том числе у пожилых), при длительном применении больших доз аминогликозидов, гипокалиемии и дегидратации, миастении, одновременном назначении миорелаксантов и лекарственных средств, снижающих канальцевую секрецию. У детей раннего возраста, а также у взрослых при быстром внутривенном введении и внутриполостном (внутрибрюшном и внутриплевральном) назначении больших доз могут возникать нарушения дыхания вследствие нервно-мышечного блока.", Effect="Амикацин - антибиотик широкого спектра действия с преимущественным влиянием на грамотрицательные бактерии. Амикацин — наиболее эффективный аминогликозид, подавляющий микрофлору, устойчивую к аминогликозидам I и II поколения, а в ряде случаев — и к нетилмицину.", MethodsOfUse="Внутримышечно или внутривенно по 0,01—0,015 г/кг в сутки в 2—3 приема. Первоначальная однократная доза амикацина — 7,5 мг/кг. Продолжительность курса лечения обычно составляет 7-10 дней; более длительное применение аминогликозидов возможно лишь по очень строгим показаниям.", StorageCondition="2 г.", Image=@"\imgMed\3.jpg"},
            new Medicine{Name="Алфинор", Type="Таблетки", Country="НИДЕРЛАНДЫ", Company="Farmaceutisch Analytisch Laboratorium Duiven B.V", Recipe=true, Dosage="8 Миллиграмм", InternationalName="Бетагистин", Component="лактозы моногидрат, крахмал кукурузный, целлюлоза микрокристаллическая (Тип 102), кислота лимонная безводная, повидон К 25, кросповидон (Тип А), масло растительное гидрогенизированное", PharmaAction="Препараты для лечения заболеваний нервной системы другие. Средство для устранения головокружения.", Contrindiction="повышенная чувствительность к бетагистина гидрохлориду или к любому другому компоненту препарата феохромоцитома; беременность и период лактации; детский и подростковый возраст до 18 лет; непереносимость глюкозы, недостаточность лапп-лактазы, синдром мальабсорбции глюкозы/галактозы", Effect="тошнота, рвота, изжога, боль в эпигастральной области, метеоризм (указанные симптомы будут менее выражены, если принимать препарат во время еды, или уменьшить дозировку)", MethodsOfUse="Для приема внутрь. Таблетки рекомендуется принимать во время или сразу после приема пищи. Стандартная доза: 24 мг-48 мг в день, разделенные на 2-3 приема. Максимальная суточная доза составляет 48 мг, разделенные на 2-3 приема. На протяжении курса лечения дозу корректируют в зависимости от терапевтического эффекта.", StorageCondition="3 г.", Image=@"\imgMed\4.jpg"},
            new Medicine{Name="Нифуроксазид", Type="Таблетки, покрытые оболочкой", Country="УКРАИНА", Company="Тернофарм ООО", Recipe=true, Dosage="0.1 Грамм", InternationalName="Нифуроксазид", Component="целлюлоза микрокристаллическая, повидон, лактоза моногидрат, кальция стеарат", PharmaAction="инфекционная диарея у взрослых, хронические колиты, энтероколиты – в качестве вспомогательного средства в комплексном лечении дисбиоза кишечника", Contrindiction="повышенная чувствительность к производным 5-нитрофурана и/или другим компонентам препарата; детский и подростковый возраст до 18 лет; наследственная непереносимость фруктозы, дефицит фермента Lapp-лактазы, мальабсорбция глюкозы-галактозы", Effect="кратковременная боль в животе, тошнота, усиление диареи", MethodsOfUse="Нифуроксазид применяют перорально, независимо от приема пищи, по 1 таблетке 4 раза в сутки (суточная доза – 800 мг). Курс лечения – 5 – 7 дней", StorageCondition="2 г.", Image=@"\imgMed\5.jpg"},
            new Medicine{Name="Мореназал", Type="Капли назальные", Country="РОССИЯ", Company="Синтез ОАО", Recipe= false, Dosage="Нет информации", InternationalName="Нет", Component="соль морская (в пересчете на сухое вещество) – 1,08 г, натрий – не менее 2,5 мг/мл, магний – не менее 0,35 мг/мл, кальций – не менее 0,008 мг/мл, калий – не менее 0,10 мг/мл, гидрокарбонаты – не менее 0,03 мг/мл",PharmaAction="аденоиды; острый, аллергический, вазомоторный ринит; профилактика инфекций полости носа в осенне-зимний период, при изменении климатических условий (помещения с кондиционированием воздуха и/или центральным отоплением); загрязненный атмосферный воздух (курильщики, водители автотранспорта, горячие и запыленные цеха); подготовка к введению в полость носа других лекарственных средств (для улучшения их всасывания)", Contrindiction="повышенная чувствительность к компонентам препарата", Effect="аллергические реакции", MethodsOfUse="Интраназально (в носовые ходы). Капли Мореназал предназначены для детей раннего возраста (до 6 лет), вклю-чая и детей до 1 года, но возможно их применение и у детей более старшего возраста. Пациентам старше 1 года можно назначать Мореназал спрей назальный.", StorageCondition="2 г.", Image=@"\imgMed\6.jpg"},
            new Medicine{Name="Волвит™", Type="Таблетки, покрытые оболочкой", Country="ИНДИЯ", Company="Кусум Хелткер Пвт. Лтд", Recipe=false, Dosage="5 Миллиграмм", InternationalName="Биотин", Component="Opadry II 85 G 54348 Розовый (спирт поливиниловый, тальк, макрогол/PEG 3350, лецитин, понсо 4R алюминиевый лак (Е 124), титана диоксид (Е 171), хинолиновий желтый алюминиевый лак (Е 104)", PharmaAction="Комплексное лечение и профилактика заболеваний, вызванных дефицитом биотина у взрослых:; заболевания волос (повышенная тонкость волос, секущиеся и ломкие волосы, выпадение волос, повышенная жирность или сухость волос, седина); заболевания кожи (дерматит, жирная себорея, сухость и шелушение кожи); заболевания ногтей (ломкость, расслаивание, нарушение роста ногтей или их структуры)", Contrindiction="повышенная чувствительность к биотину или другим компонентам препарата; детский и подростковый возраст до 18 лет; беременность и период лактации", Effect="одышка; аллергические реакции в виде кожных высыпаний, крапивницы", MethodsOfUse="Таблетки ВолвитТМ применяют внутрь до еды, запивая небольшим количеством воды. Рекомендованная доза при лечении заболеваний ногтей, волос, кожи и нарушений со стороны нервной системы составляет 5 мг в сутки", StorageCondition="2 г.", Image=@"\imgMed\7.jpg"},
            new Medicine{Name="Дексаметазон", Type="Раствор для инъекций", Country="БЕЛАРУСЬ", Company="Белмедпрепараты РУП", Recipe=true, Dosage="4 Миллиграмм на миллилитр", InternationalName="Дексаметазон", Component="натрия дексаметазона фосфат (эквивалентно дексаметазону фосфату) 4.37 мг (4.00 мг)", PharmaAction="шок различного генеза (анафилактический, посттравматический, послеопе-рационный, кардиогенный, гемотрансфузионный и др.); отёк головного мозга (при опухолях головного мозга, черепно-мозговой травме, нейрохирургических операциях, кровоизлиянии в мозг, менингитах, энцефалитах, лучевых поражениях); астматический статус; тяжелые аллергические реакции (отек Квинке, бронхоспазм, дерматоз, острая анафилактическая реакция на лекарственные препараты, переливание сыворотки, пирогенные реакции); острая гемолитическая анемия; тромбоцитопения; агранулоцитоз; острая лимфобластная лейкемия", Contrindiction="повышенная чувствительность к дексаметазону или вспомогательным компонентам препарата; системная инфекция, в случае если не используется специфическая антибактериальная терапия", Effect="Обычно Дексаметазон хорошо переносится. Он обладает низкой минералокортикоидной активностью: его влияние на водно-электролитный обмен невелико. Как правило, низкие и средние дозы Дексаметазона не вызывают задержки натрия и воды в организме, повышенной экскреции калия", MethodsOfUse="Режим дозирования является индивидуальным и зависит от показаний, тяжести заболевания и реакции пациента на терапию. Препарат вводят внутримышечно, внутривенно медленно струйно или капельно, возможно также периартикулярное или внутрисуставное введение. С целью приготовления раствора для в/в капельной инфузии следует использовать изотонический раствор натрия хлорида, 5% раствор глюкозы или раствор Рингера", StorageCondition="3 г.", Image=@"\imgMed\8.jpg"},
            new Medicine{Name="Алмирал", Type="Раствор для инъекций", Country="КИПР", Company="Медокеми Лтд", Recipe=true, Dosage="75мг/3мл", InternationalName="Диклофенак", Component="1 мл препарата содержит: пропиленгликоль, спирт бензиловый, натрия формальдегида сульфоксилат, натрия метабисульфит (Е 223), натрия гидроксид, вода для инъекций", PharmaAction="острый болевой синдром вследствие воспаления или дегенеративных форм ревматизма; ревматоидный артрит; анкилозирующий спондилит", Effect="тошнота, рвота, анорексия, запор, диарея; головная боль, головокружение, бессонница, нарушение памяти, тремор, судороги", Contrindiction="гиперчувствительность к диклофенаку или к любому из ингредиентов препарата; эрозивно-язвенные поражения ЖКТ в стадии обострения или в анамнезе", MethodsOfUse="В случае почечной колики назначают одну ампулу (75мг) внутримышечно, следующая доза (75мг) может быть введена при необходимости через 30 минут. Максимальная доза для взрослых не должна превышать 150мг", StorageCondition="3 г.", Image=@"\imgMed\9.jpg"},
            new Medicine{Name="Эффералган", Type="Раствор для приема внутрь", Country="ФРАНЦИЯ", Company="Бристол-Майерс Сквибб", Recipe=false, Dosage="Нет", InternationalName="Парацетамол", Component="парацетамол, макрогол-6000, сахарный сироп, сахарин натрия Е 954, калия сорбат, кислота лимонная безводная, ароматизатор карамельно-ванильный *, вода очищенная. * состав: гамма-окталактон, гамма-гексалактон, диацетил, ацетилметилкарбинол, изоаммил циннамат, гамма-гепталактон, ванилин, пропиленгликоль, триацетин, карамельный краситель", PharmaAction="Симптоматическое лечение болей от легкой до умеренной интенсивности и/или фебрильных состояний", Effect="анафилактический шок, отек Квинке, эритема, крапивница и кожная сыпь", Contrindiction="повышенная чувствительность к парацетамолу или к какому-либо из вспомогательных ингредиентов препарата; гепатоцеллюлярная недостаточность; детский возраст до 1месяца", MethodsOfUse="Эффералган предназначен для детей с массой тела от 4 до 32 кг (возрастом приблизительно 1 месяц – 12 лет). Раствор можно принимать внутрь в неразбавленном виде или разбавленным в небольшом количестве жидкости (например, воды, молока, сока). У детей следует соблюдать дозирование в соответствии с массой тела ребёнка. Возраст и соответствующая ему масса тела приводятся ориентировочно. Рекомендованная суточная доза парацетамола составляет около 60 мг/кг/день. Средняя разовая доза Эффералгана зависит от массы тела ребенка и составляет 10-15 мг/кг массы тела каждые 6 часов 4 раза в сутки.", StorageCondition="3 г.", Image=@"\imgMed\10.jpg"}
            };
            medicines.ForEach(s => context.Medicines.Add(s));
            context.SaveChanges();
        }

    }
}